Článok 26.
Každý má právo na vzdelanie. Vzdelanie nech je bezplatné aspoň v začiatočných a základných stupňoch. Základné vzdelanie je povinné. Technické a odborné vzdelanie nech je všeobecne prístupné a vyššie vzdelanie má byť rovnako prístupné každému podľa jeho schopností.
Vzdelanie má smerovať k plnému rozvoju ľudskej osobnosti a k posilneniu úcty k ľudským právam a základným slobodám. Má napomáhať k vzájomnému porozumeniu, snášanlivosti a priateľstvu medzi všetkými národmi a všetkými rasovými i náboženskými skupinami, ako aj k rozvoju činnosti Spojených národov pre zachovanie mieru.
Rodičia majú prednostné právo voliť druh vzdelania pre svoje deti.
Článok 27.
Každý má právo slobodne sa účastniť na kultúrnom živote spoločnosti, užívať plodov umenia a účastniť sa na vedeckom pokroku a jeho výťažkoch.
Každý má právo na ochranu morálnych a materiálnych záujmov, ktoré vyplývajú z jeho vedeckej, literárnej alebo umeleckej tvorby.